# Generated by Django 4.0.6 on 2023-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
