# Generated by Django 4.0.6 on 2023-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_student_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
