# Generated by Django 4.0.6 on 2023-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_student_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
